play.http.secret.key = "CHANGE_THIS_SECRET"

search.uri = "http://elasticsearch:9200"

db.janusgraph {
  storage.backend = cql
  storage.hostname = ["cassandra"]
  storage.cql.cluster-name = thehive
  storage.cql.keyspace = cortex
}

auth.provider = [local]

job.runner = docker
job.dockerBasePath = "/tmp/cortex-jobs"
