[Failed Login Attempts]
search = index=main ("Failed password" OR "authentication failure" OR EventCode=4625) | stats count by host | where count > 5
cron_schedule = */5 * * * *
enableSched = 1
alert.severity = 3

[Web Enumeration 404 Detection]
search = index=main apache-access 404 | stats count by host | where count > 10
cron_schedule = */5 * * * *
enableSched = 1
alert.severity = 2

[Privilege Escalation Detection]
search = index=main sudo | stats count by host | where count > 20
cron_schedule = */10 * * * *
enableSched = 1
alert.severity = 3

[SQL Injection Attempt]
search = index=main apache-access ("select" OR "union" OR "drop" OR "1=1") | stats count by host
cron_schedule = */5 * * * *
enableSched = 1
alert.severity = 4

[XSS Attempt]
search = index=main apache-access ("<script>" OR "javascript:" OR "onerror=") | stats count by host
cron_schedule = */5 * * * *
enableSched = 1
alert.severity = 4
