play.http.secret.key = "CHANGE_THIS_SECRET"

db {
  provider = janusgraph
  janusgraph {
    storage.backend = cql
    storage.hostname = ["cassandra"]
    storage.cql.cluster-name = thehive
    storage.cql.keyspace = thehive

    index.search.backend = elasticsearch
    index.search.hostname = ["elasticsearch"]
    index.search.index-name = thehive
  }
}

storage.provider = localfs
storage.localfs.location = /opt/thehive/data

play.modules.enabled += org.thp.thehive.connector.cortex.CortexModule
cortex {
  servers = [
    {
      name = "local"
      url = "http://cortex:9001"
      auth {
        type = bearer
        key = "6Lv84PO0Xi/EfuXyg2+RSC/wKKpko6UL"
      }
    }
  ]
}

play.modules.enabled += org.thp.thehive.connector.misp.MispModule

misp {
  interval = 5 min 
  
  servers = [
    {
      name = "local-misp"
      url = "http://misp-core"
      
      auth {
        type = key
        key = "NOlJg7T1uDhYsnKcwmZ5gurry7WMsBOBGiAtsF3c"
      }
      
      purpose = ImportAndExport
      
      wsConfig {
        ssl {
          loose {
            acceptAnyCertificate = true
          }
        }
      }
      
      caseTemplate = "misp-event"
      tags = ["tlp:white", "tlp:green", "tlp:amber"]
      max-attributes = 1000
      max-age = 7
      
      exclusion {
        tags = ["tlp:red", "do-not-share"]
      }
    }
  ]
}
