LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %D" combined_security
CustomLog /var/log/apache2/access.log combined_security
CustomLog /var/log/apache2/security.log "%h %t \"%r\" %>s %b \"%{User-Agent}i\""
ErrorLog /var/log/apache2/error.log
LogLevel warn
